version: '3.1'

services:
    quizzoto_web:
        image: node:hydrogen-slim
        container_name: quizzotoV2
        command: /bin/sh -c "cd /srv/app && npm install && npm run dev"
        ports:
            - 3001:3000
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
        tty: true
